api_create_post:
    path: /api/post
    methods: POST
    controller: App\Blog\Infrastructure\Controllers\Api\CreatePostController

api_edit_post:
    path: /api/post
    methods: PATCH
    controller: App\Blog\Infrastructure\Controllers\Api\EditPostController

api_get_posts:
    path: /api/post
    methods: GET
    controller: App\Blog\Infrastructure\Controllers\Api\GetPostsController

api_create_tag:
    path: /api/tag
    methods: POST
    controller: App\Blog\Infrastructure\Controllers\Api\CreateTagController

api_create_user:
    path: /api/user
    methods: POST
    controller: App\Core\Infrastructure\Controllers\Api\CreateUserController